### ISSUE TITLE
How to setup batchSize and batchWindow with this Serverless Dynamo Stream Plugin

### ISSUE THREAD

**Issue by MeRahulAhire** [commandeer/open#195]
I came across this plugin and want to know that how can I manually setup `batchSize` and `batchWindow` with this plugin.

I tried the following
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - existingDynamoStream:
          tableName: newTable
          streamType: NEW_AND_OLD_IMAGES
          startingPosition: LATEST
          batchSize : 50
```
and shows me this one
```bash
Serverless: Configuration warning:
Serverless:   at 'functions.hello.events[0].existingDynamoStream': unrecognized property 'batchSize'
```
and
