### ISSUE TITLE
Localstack Cloudformation Data Missing

### ISSUE THREAD

**Issue by OskergMonReap** [commandeer/open#45]
**Commandeer version**: 0.6.0
Installed across multiple Linux Distro's via **AppImage**
**Localstack version**: 0.10.8  [started via `localstack start` command]
**Further details**: all testing has been done using `awscli-local` to interact with localstack

**Issue**: Although all resources created by Cloudformation within localstack appear without issue, Cloudformation itself never populates any data. Tested by creating several very simple Cloudformation stacks, ie creating S3 buckets, SQS queues etc..
Cloudformation within the Dashboard endlessly refreshes with no change

**Expected**: To see stack data, even if it's just the number of stacks currently deployed in localstack, within the Dashboards

**Comment by OskergMonReap** [comment]
Account data file contents:
```
{
    "isLocal":true,
    "isProduction":false,
    "id":"63fdc0b7-ecb2-4eef-9988-92a1121dae5e",
    "name":"local",
    "algolia":{"applicationId":"","apiKey":""},
    "aws":{
        "region":"us-east-1",
        "accessKeyId":"NO_LOCAL_ACCESS_KEY_ID",
        "secretAccessKey":"NO_LOCAL_SECRET_ACCESS_KEY",
        "apigatewayEndpoint":"http://localhost:4567",
        "cloudwatchEndpoint":"http://localhost:4582",
        "cloudwatchLogsEndpoint":"http://localhost:4586",
        "cloudwatchEventsEndpoint":"http://localhost:4587",
        "dynamoEndpoint":"http://localhost:4569",
        "ec2Endpoint":"http://localhost:4597",
        "iamEndpoint":"http://localhost:4593",
        "lambdaEndpoint":"http://localhost:4574",
        "s3Endpoint":"http://localhost:4572",
        "s3Prefix":"",
        "snsEndpoint":"http://localhost:4575",
        "sqsEndpoint":"http://localhost:4576"
    },
    "database"{
        "host":"",
        "initialDatabase":"",
        "username":"",
        "password":"",
        "type":"POSTGRES"
    },
    "slack":{"token":""}
}
```

**Commands ran**: Initially tested with a very simple cloudformation stack that just created a bucket with no real configuration, sample template:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample template to create a bucket with Retain on delete'
Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
        DeletionPolicy: Retain
```
Then deployed locally via `awslocal cloudformation create-stack --stack-name tests3stack --template-body file://S3_bucket_retain.yml`
--> confirmed stack deployed succesfully via `awslocal cloudformation list-stacks` and verifying the S3 bucket was created and present in the S3 Commandeer dashboard

The Cloudformation dashboard unfortunately never showed any stack details

**Comment by mengelseatz** [comment]
I'm seeing similar although slightly different things.  I have a simple CF stack with SNS, SQS and S3 and deployed in localstack using the awslocal command line and only S3 and SNS show up as being created.   CF shows my stack but there is no information about the stack in the viewer (although maybe that's just the way it currently looks - basically it just gives you a simple status page?).  

But the SQS queue that's missing is the bug I'm seeing.  Note that my SNS topic which is subscribed to by a queue shows the subscription but the subscription section shows the SQS queue but it's greyed out.   One thing to note is that I currently haven't given the queue proper IAM permissions yet but when I build this same template in AWS CloudFormation console all the resources are built and accessible.    And as I mentioned the SQS queue is there in Localstack if I look at it with the  command line tools and I can send/receive messages to it.

**Comment by mengelseatz** [comment]
Using the non-edge SQS port of 4576 for docker-compose.yml and in Commandeer didn't resolve the issue.  See attached screenshot of sidebar

<img width="401" alt="Screen Shot 2020-07-19 at 8 13 09 AM" src="https://user-images.githubusercontent.com/46827169/87874443-d17b8800-c997-11ea-9842-7522b371411c.png">

**Comment by fsproru** [comment]
@mengelseatz would you mind sending the instructions and the template configuration you ran to create the stack so we can reproduce it on our end?

**Comment by mengelseatz** [comment]
Sure thing @fsproru 

CloudFormation template yaml
```
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SiteConfigS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: site-config-s3-local
  SlogWorkerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: slog-worker-queue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
          - SlogWorkerDLQ
          - Arn
        maxReceiveCount: 1
  SlogWorkerDLQ:
    Type: AWS::SQS::Queue
  SlogSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Fn::GetAtt:
          - SlogWorkerDLQ
          - Arn
        Protocol: sqs
      TopicName: SlogEventTopic

```

relevant docker-compose.yml for Localstack
```
  localstack:
    privileged: true
    image: localstack/localstack:latest
    ports:
    - 4566:4566
    environment:
    - SERVICES=sqs,sns,s3,cloudformation,dynamodb,iam,apigateway,lambda
    - HOSTNAME=localstack
    - DOCKER_HOST=unix:///var/run/docker.sock
    - DEFAULT_REGION=us-east-1
    - DEBUG=0
    volumes:
    - "./.localstack:/tmp/localstack"
    - "./site_config/cloudformation:/docker-entrypoint-initaws.d"
    - "/var/run/docker.sock:/var/run/docker.sock"

```

and lastly this command is run from inside the Localstack container to create the AWS resources

`awslocal cloudformation deploy --template-file /docker-entrypoint-initaws.d/template.yml --region us-east-1 --stack-name iz-localstack`

Let me know if you need anything else or want me to test anything.. I'm hoping to get this working so we I can get approval to use Commandeer for our microservices dev team.
