### ISSUE TITLE
serverless-dynamo-stream-plugin configValidationMode: warn warning

### ISSUE THREAD

**Issue by rpinna** [commandeer/open#80]
Thank you for writing the much-needed `serverless-dynamo-stream-plugin`  plugin.

fyi, with

`configValidationMode: warn`

serverless generates

```
Serverless: Configuration warning at 'functions['on-mutation'].events[0]': unsupported function event
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

on this version

```sh
$ .../node_modules/.bin/serverless --version
Building profileKey dev
Framework Core: 2.4.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

for this yaml

```yaml
service: conversation-message
configValidationMode: warn
frameworkVersion: '>=2.4.0'
custom:
  webpack:
    ...
package:
  individually: true
plugins:
  - serverless-webpack
  - serverless-plugin-git-variables
  - serverless-dynamo-stream-plugin
provider:
  ...
functions:
  on-mutation:
    handler: src/index.handler
    environment:
      mode: enabled
    events:
      - existingDynamoStream:
          tableName: ConversationMessage-rrx7agecrbelvawcvl7gvz2khm-dev
          streamType: NEW_AND_OLD_IMAGES
          startingPosition: LATEST
    name: conversation-message-dev-on-mutation
```
